version: '3.8'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://api:p@ssw0rd@db:5432/project-board
    volumes:
      - ./src:/app/src # srcディレクトリの変更をリアルタイムで反映
      - ./prisma:/app/prisma # prismaディレクトリの変更をリアルタイムで反映
      - ./package.json:/app/package.json # package.jsonの変更を反映
      - ./tsconfig.json:/app/tsconfig.json # tsconfig.jsonの変更を反映
      - ./bun.lockb:/app/bun.lockb # bun.lockbの変更を反映
      - /app/node_modules # node_modulesディレクトリをコンテナに固定
    networks:
      - project-board
  db:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: project-board
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - project-board
  test-db:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: test-project-board
    ports:
      - '5433:5432'
    networks:
      - project-board
networks:
  project-board:
    driver: bridge
