name: testing

on:
  pull_request:
    branches: ['main', 'develop']

jobs:
  unit-testing:
    name: unit-testing
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2-bullseye
        env:
          POSTGRES_USER: api
          POSTGRES_PASSWORD: p@ssw0rd
          POSTGRES_DB: project-board
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run unit tests
        run: bun run test

      - name: Shutdown Docker Compose
        run: docker-compose -f docker-compose.yml down
